let inventoryData=[],requestList=[],approvedList=[],entryList=[],returnList=[],reportData=[],tadaList=[],currentTadaData=[],currentImgBase64="",selectedInventory=null;
function saveData(){localStorage.setItem("inv",JSON.stringify(inventoryData));localStorage.setItem("req",JSON.stringify(requestList));localStorage.setItem("app",JSON.stringify(approvedList));localStorage.setItem("ent",JSON.stringify(entryList));localStorage.setItem("ret",JSON.stringify(returnList));localStorage.setItem("rep",JSON.stringify(reportData));localStorage.setItem("tada",JSON.stringify(tadaList));}
function loadData(){inventoryData=JSON.parse(localStorage.getItem("inv")||"[]");requestList=JSON.parse(localStorage.getItem("req")||"[]");approvedList=JSON.parse(localStorage.getItem("app")||"[]");entryList=JSON.parse(localStorage.getItem("ent")||"[]");returnList=JSON.parse(localStorage.getItem("ret")||"[]");reportData=JSON.parse(localStorage.getItem("rep")||"[]");tadaList=JSON.parse(localStorage.getItem("tada")||"[]");}
function getFiltered(list){if(!currentUser||currentUser.role=="admin")return list;return list.filter(r=>r.user==currentUser.id);}
function toggleTheme(){document.body.classList.toggle("light");}
function showTab(id){if(id=="users"&&currentUser.role!="admin"){alert("Only admin");return;}if(currentUser.role!="admin"){if(currentUser.pages&&currentUser.pages[id]===false){alert("Permission nahi hai");return;}if(id=="report"&&currentUser.reportPerm&&!currentUser.reportPerm.view){alert("Report View nahi hai");return;}}document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));document.querySelectorAll('.sidebar button').forEach(b=>b.classList.remove('active'));document.getElementById(id).classList.add('active');let btn=document.getElementById('nav_'+id)||document.getElementById('btnUsers');if(btn)btn.classList.add('active');}
function renderAll(){renderUsers();renderInventory();renderRequest();renderApproval();renderDispatch();renderEntry();renderSend();renderReport();renderStock();renderTada();}
function addUser(){if(!uId.value||!uPass.value){alert("ID Pass required");return;}let pages={inventory:pg_inventory.checked,request:pg_request.checked,approval:pg_approval.checked,dispatch:pg_dispatch.checked,entry:pg_entry.checked,send:pg_send.checked,report:pg_report.checked,stock:pg_stock.checked,tada:pg_tada.checked};let reportPerm={view:rp_view.checked,export:rp_export.checked,edit:rp_edit.checked};let existing=usersList.findIndex(x=>x.id==uId.value.trim());let obj={id:uId.value.trim(),pass:uPass.value.trim(),role:uRole.value,loc:uLoc.value.trim()||"Kolhapur",pages,reportPerm};if(existing>=0){usersList[existing]=obj;}else{usersList.push(obj);}saveUsers();renderUsers();uId.value=uPass.value=uLoc.value="";alert("User saved");}
function renderUsers(){usersTable.innerHTML=`<tr><th>User ID</th><th>Pass</th><th>Role</th><th>Location</th><th>Page Access</th><th>Report Perm</th><th>Action</th></tr>`;usersList.forEach((u,i)=>{let pg=u.pages?Object.keys(u.pages).filter(k=>u.pages[k]).map(k=>k.substring(0,3)).join(', '):'all';let rp=u.reportPerm?`${u.reportPerm.view?'View ':''}${u.reportPerm.export?'Exp ':''}${u.reportPerm.edit?'Edit':''}`:'-';usersTable.innerHTML+=`<tr><td>${u.id}</td><td>${u.pass}</td><td>${u.role}</td><td>${u.loc}</td><td style="font-size:10px">${pg}</td><td style="font-size:10px">${rp}</td><td><button class="btn-edit" onclick="editUser(${i})">Edit</button> ${u.id!='admin'?`<button class="btn-del" onclick="delUser(${i})">Del</button>`:''}</td></tr>`;});}
function editUser(i){let u=usersList[i];uId.value=u.id;uPass.value=u.pass;uRole.value=u.role;uLoc.value=u.loc;if(u.pages){pg_inventory.checked=u.pages.inventory;pg_request.checked=u.pages.request;pg_approval.checked=u.pages.approval;pg_dispatch.checked=u.pages.dispatch;pg_entry.checked=u.pages.entry;pg_send.checked=u.pages.send;pg_report.checked=u.pages.report;pg_stock.checked=u.pages.stock;pg_tada.checked=u.pages.tada;}if(u.reportPerm){rp_view.checked=u.reportPerm.view;rp_export.checked=u.reportPerm.export;rp_edit.checked=u.reportPerm.edit;}}
function delUser(i){if(usersList[i].id=="admin"){alert("Cannot delete admin");return;}if(confirm("Delete "+usersList[i].id+"?")){usersList.splice(i,1);saveUsers();renderUsers();}}
function previewImg(e){let file=e.target.files[0];let reader=new FileReader();reader.onload=function(){currentImgBase64=reader.result;invImgPreview.src=currentImgBase64;};reader.readAsDataURL(file);}
function addInventory(){if(!invMat.value||!invPart.value){alert("Required");return;}let obj={name:invMat.value.trim(),part:invPart.value.trim(),cat:invCat.value,manu:invManu.value,img:currentImgBase64,createdBy:currentUser.id};inventoryData.push(obj);saveData();renderInventory();invMat.value=invPart.value=invManu.value='';invImgPreview.src='';currentImgBase64='';}
function renderInventory(){inventoryData.sort((a,b)=>a.cat.localeCompare(b.cat));invTable.innerHTML=`<tr><th>Category</th><th>Material</th><th>Part No</th><th>By</th><th>Image</th><th>Action</th></tr>`;inventoryData.forEach((d,i)=>{invTable.innerHTML+=`<tr><td>${d.cat}</td><td>${d.name}</td><td>${d.part}</td><td>${d.createdBy||'-'}</td><td><img src="${d.img}" width="40"></td><td><button class="btn-del" onclick="deleteInv(${i})">Delete</button></td></tr>`;});}
function deleteInv(i){if(confirm("Delete?")){inventoryData.splice(i,1);saveData();renderInventory();}}
function importExcel(e){let file=e.target.files[0];let reader=new FileReader();reader.onload=function(evt){let data=new Uint8Array(evt.target.result);let wb=XLSX.read(data,{type:'array'});let ws=wb.Sheets[wb.SheetNames[0]];let json=XLSX.utils.sheet_to_json(ws);json.forEach(row=>{inventoryData.push({name:row['Material Name']||row['name']||'',part:row['Part No']||row['part']||'',cat:row['Category']||'Other',manu:row['Manufacturer']||'',img:'',createdBy:currentUser.id})});saveData();renderInventory();};reader.readAsArrayBuffer(file);}
function searchInventory(){let q=searchMatInput.value.toLowerCase().trim();let s=document.getElementById("searchSuggest");if(q.length<1){s.style.display="none";return;}let f=inventoryData.filter(d=>d.name.toLowerCase().includes(q)||d.part.toLowerCase().includes(q));if(f.length==0){s.innerHTML="<div>No result</div>";s.style.display="block";return;}s.innerHTML=f.slice(0,20).map(d=>`<div onclick="selectMaterial('${d.name.replace(/'/g,"\\'")}')"><b>${d.name}</b> - ${d.part}</div>`).join('');s.style.display="block";}
function selectMaterial(name){let sel=inventoryData.find(d=>d.name==name);if(!sel)return;selectedInventory=sel;reqMat.value=sel.name;reqPart.value=sel.part;reqCat.value=sel.cat;reqImg.src=sel.img||'';document.getElementById("searchSuggest").style.display="none";searchMatInput.value=sel.name;}
document.addEventListener('click',function(e){if(!e.target.closest('.searchBox')){let el=document.getElementById("searchSuggest");if(el)el.style.display="none";}});
function sendRequest(){if(!selectedInventory){alert("Select material");return;}if(!reqQty.value){alert("Qty dalo");return;}let obj={user:currentUser.id,mat:selectedInventory.name,part:selectedInventory.part,cat:selectedInventory.cat,qty:reqQty.value,status:"Pending",date:new Date().toLocaleDateString(),loc:currentUser.loc};requestList.push(obj);saveData();renderRequest();renderApproval();reqQty.value='';reqMat.value='';reqPart.value='';reqCat.value='';}
function renderRequest(){let data=getFiltered(requestList);requestTable.innerHTML=`<tr><th>User</th><th>Loc</th><th>Material</th><th>Part</th><th>Qty</th><th>Status</th><th>Date</th></tr>`;data.forEach(r=>requestTable.innerHTML+=`<tr><td>${r.user}</td><td>${r.loc||'-'}</td><td>${r.mat}</td><td>${r.part}</td><td>${r.qty}</td><td>${r.status}</td><td>${r.date}</td></tr>`);}
function renderApproval(){let data=currentUser.role=="admin"?requestList:requestList.filter(r=>r.user==currentUser.id);approvalTable.innerHTML=`<tr><th>User</th><th>Loc</th><th>Material</th><th>Qty</th><th>Edit Qty</th><th>Action</th></tr>`;data.forEach(r=>{let ri=requestList.indexOf(r);if(r.status=="Pending"){approvalTable.innerHTML+=`<tr><td>${r.user}</td><td>${r.loc}</td><td>${r.mat}</td><td>${r.qty}</td><td><input type="number" id="editQty${ri}" value="${r.qty}" style="width:80px"></td><td><button style="background:#16a34a" onclick="approve(${ri})">Approve</button> <button class="btn-del" onclick="rejectReq(${ri})">Reject</button></td></tr>`;}});}
function approve(i){let nq=document.getElementById(`editQty${i}`).value;requestList[i].status="Approved";requestList[i].qty=nq;approvedList.push({...requestList[i],serial:"",pod:"",date:"",adminCond:"Good"});saveData();renderApproval();renderRequest();renderDispatch();}
function rejectReq(i){requestList[i].status="Rejected";saveData();renderApproval();renderRequest();}
function renderDispatch(){let data=getFiltered(approvedList);dispatchTable.innerHTML=`<tr><th>User</th><th>Material</th><th>Part</th><th>Serial</th><th>Cond</th><th>POD</th><th>Date</th><th>Action</th></tr>`;data.forEach(r=>{let ri=approvedList.indexOf(r);dispatchTable.innerHTML+=`<tr><td>${r.user}</td><td>${r.mat}</td><td>${r.part}</td><td><input id="ser${ri}" placeholder="Serial"></td><td><select id="condD${ri}"><option>Good</option><option>Faulty</option></select></td><td><input id="pod${ri}" placeholder="POD"></td><td><input type="date" id="date${ri}"></td><td><button style="background:#16a34a" onclick="sendDispatch(${ri})">Send</button></td></tr>`;});}
function sendDispatch(i){let rec=approvedList[i];rec.serial=document.getElementById(`ser${i}`).value;rec.adminCond=document.getElementById(`condD${i}`).value;rec.pod=document.getElementById(`pod${i}`).value;rec.dispatchDate=document.getElementById(`date${i}`).value;rec.date=rec.dispatchDate;if(!rec.serial||!rec.pod||!rec.dispatchDate){alert("Fill all");return;}entryList.push({...rec});reportData.push({dispatchDate:rec.dispatchDate,user:rec.user,loc:rec.loc,oldMat:rec.mat,oldPart:rec.part,oldSerial:rec.serial,mat:rec.mat,part:rec.part,serial:rec.serial,adminPod:rec.pod,userStatus:"Dispatched",detail:"Dispatch Qty:"+rec.qty,replaceTo:"-",newPart:"-",newSerial:"-",sendPod:"-",sendDate:"-",condition:rec.adminCond,qty:rec.qty});approvedList.splice(i,1);saveData();renderDispatch();renderEntry();renderReport();renderStock();}
function renderEntry(){let data=getFiltered(entryList);entryTable.innerHTML=`<tr><th>User</th><th>Material</th><th>Part</th><th>Serial</th><th>POD</th><th>Status</th><th>Detail</th><th>Cond</th><th>Action</th></tr>`;data.forEach(r=>{let ri=entryList.indexOf(r);entryTable.innerHTML+=`<tr><td>${r.user}</td><td>${r.mat}</td><td>${r.part}</td><td>${r.serial}</td><td>${r.pod}</td><td><select id="status${ri}" onchange="toggleReplace(${ri})"><option>Available</option><option>Used</option><option>Replace</option><option>Return</option></select></td><td id="replaceTd${ri}">-</td><td><select id="cond${ri}"><option>Good</option><option>Faulty</option></select></td><td><button class="btn-edit" onclick="saveEntry(${ri})">Update</button></td></tr>`;});}
function toggleReplace(i){let v=document.getElementById(`status${i}`).value;let td=document.getElementById(`replaceTd${i}`);if(v=="Replace"){td.innerHTML=`<select id="sameDiff${i}" onchange="showNewMat(${i})"><option>Same</option><option>Different</option></select><div id="newMatDiv${i}" style="display:none"><select id="newMat${i}"></select><input id="newSer${i}" placeholder="New Serial"><input id="side${i}" placeholder="Side Code"></div><input id="sideSame${i}" placeholder="Side Code">`;document.getElementById(`newMat${i}`).innerHTML='<option>Select</option>'+inventoryData.map(d=>`<option value="${d.name}">${d.name} - ${d.part}</option>`).join('');}else if(v=="Return"){td.innerHTML=`<input id="side${i}" placeholder="Side Code">`;}else{td.innerHTML="-";}}
function showNewMat(i){let v=document.getElementById(`sameDiff${i}`).value;document.getElementById(`newMatDiv${i}`).style.display=v=="Different"?"block":"none";document.getElementById(`sideSame${i}`).style.display=v=="Different"?"none":"block";}
function saveEntry(i){let rec=entryList[i];let oldMat=rec.mat;let oldPart=rec.part;let oldSerial=rec.serial;rec.userStatus=document.getElementById(`status${i}`).value;rec.condition=document.getElementById(`cond${i}`).value;let detail="-",replaceTo="-",newPart="-",newSerial="-",newMatName="-";if(rec.userStatus=="Replace"){let type=document.getElementById(`sameDiff${i}`)?.value||"Same";if(type=="Different"){let newMatSelect=document.getElementById(`newMat${i}`).value;if(newMatSelect=="Select"){alert("New Material select karo");return;}let newSel=inventoryData.find(d=>d.name==newMatSelect);replaceTo=newMatSelect;newMatName=newMatSelect;newPart=newSel?newSel.part:"-";newSerial=document.getElementById(`newSer${i}`).value;rec.sideCode=document.getElementById(`side${i}`).value;detail=`Replace ${oldMat} -> ${replaceTo}`;returnList.push({...rec,mat:replaceTo,part:newPart,serial:newSerial,oldMat,oldPart,oldSerial});}else{rec.sideCode=document.getElementById(`sideSame${i}`).value;detail="Same Replace";replaceTo=oldMat;newPart=oldPart;newSerial=oldSerial;newMatName=oldMat;returnList.push({...rec,oldMat,oldPart,oldSerial});}}else if(rec.userStatus=="Return"){rec.sideCode=document.getElementById(`side${i}`).value;detail=`Return Side:${rec.sideCode}`;returnList.push({...rec,oldMat,oldPart,oldSerial});}else{detail=rec.userStatus;}reportData.push({dispatchDate:rec.date,user:rec.user,loc:rec.loc,oldMat,oldPart,oldSerial,mat:oldMat,part:oldPart,serial:oldSerial,adminPod:rec.pod,userStatus:rec.userStatus,detail,replaceTo:newMatName,newPart,newSerial,sendPod:"-",sendDate:"-",condition:rec.condition,qty:rec.qty||1});entryList.splice(i,1);saveData();renderEntry();renderSend();renderReport();renderStock();}
function renderSend(){let data=getFiltered(returnList);sendTable.innerHTML=`<tr><th>User</th><th>Material</th><th>Part</th><th>Serial</th><th>Side</th><th>Cond</th><th>POD</th><th>Date</th><th>Action</th></tr>`;data.forEach(r=>{let ri=returnList.indexOf(r);sendTable.innerHTML+=`<tr><td>${r.user}</td><td>${r.mat}</td><td>${r.part}</td><td>${r.serial}</td><td>${r.sideCode||'-'}</td><td>${r.condition}</td><td><input id="podS${ri}" placeholder="POD"></td><td><input type="date" id="dateS${ri}"></td><td><button style="background:#16a34a" onclick="sendFinal(${ri})">Send</button></td></tr>`;});}
function sendFinal(i){let rec=returnList[i];rec.sendPod=document.getElementById(`podS${i}`).value;rec.sendDate=document.getElementById(`dateS${i}`).value;if(!rec.sendPod||!rec.sendDate){alert("Fill");return;}for(let k=reportData.length-1;k>=0;k--){let r=reportData[k];if(r.user==rec.user&&(r.oldSerial==rec.oldSerial||r.newSerial==rec.serial)&&r.sendPod=="-"){r.sendPod=rec.sendPod;r.sendDate=rec.sendDate;break;}}returnList.splice(i,1);saveData();renderSend();renderReport();renderStock();}
function filterReport(){let u=document.getElementById("searchUser")?.value.toLowerCase()||"";let m=document.getElementById("searchMat")?.value.toLowerCase()||"";let s=document.getElementById("searchStatus")?.value||"";let base=getFiltered(reportData);let data=base.filter(r=>(r.user||'').toLowerCase().includes(u)&&((r.oldMat||'').toLowerCase().includes(m)||(r.oldSerial||'').toLowerCase().includes(m)||(r.replaceTo||'').toLowerCase().includes(m))&&(s==""||r.userStatus==s));let tbl=document.getElementById("reportTable");if(!tbl)return;tbl.innerHTML=`<tr><th>Dispatch Date</th><th>User</th><th>Loc</th><th>Old Mat</th><th>Old Part</th><th>Old Serial</th><th>Admin POD</th><th>Status</th><th>Detail</th><th>New Mat</th><th>New Part</th><th>New Serial</th><th>Send POD</th><th>Send Date</th><th>Cond</th></tr>`;data.forEach(r=>{let isR=r.userStatus=='Replace';tbl.innerHTML+=`<tr><td>${r.dispatchDate||'-'}</td><td>${r.user}</td><td>${r.loc||'-'}</td><td><b>${r.oldMat}</b></td><td>${r.oldPart}</td><td style="color:#f59e0b">${r.oldSerial}</td><td>${r.adminPod}</td><td><span class="badge badge-${r.userStatus}">${r.userStatus}</span></td><td>${r.detail}</td><td style="color:${isR?'#22c55e':'#888'}">${isR?r.replaceTo:'-'}</td><td>${isR?r.newPart:'-'}</td><td>${isR?r.newSerial:'-'}</td><td style="color:#3b82f6;font-weight:bold">${r.sendPod}</td><td>${r.sendDate}</td><td>${r.condition}</td></tr>`;});}
function renderReport(){filterReport();}
function exportExcel(){if(currentUser.role!="admin"&&currentUser.reportPerm&&!currentUser.reportPerm.export){alert("Export permission nahi hai");return;}let ws=XLSX.utils.json_to_sheet(getFiltered(reportData));let wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Report");XLSX.writeFile(wb,"Report_"+currentUser.id+".xlsx");}
function exportPDF(){if(currentUser.role!="admin"&&currentUser.reportPerm&&!currentUser.reportPerm.export){alert("Export permission nahi hai");return;}const{jsPDF}=window.jspdf;let doc=new jsPDF('landscape');doc.text("Report - "+currentUser.id,14,15);doc.autoTable({startY:20,html:'#reportTable',styles:{fontSize:6}});doc.save("Report.pdf");}
function renderStock(){let u=document.getElementById("stockUser")?.value.toLowerCase()||"";let c=document.getElementById("stockCond")?.value||"";let available=getFiltered(entryList).filter(r=>r.user.toLowerCase().includes(u)&&(c==""||(r.condition||r.adminCond)==c));let at=document.getElementById("availableTable");if(at){at.innerHTML=`<tr><th>User</th><th>Loc</th><th>Material</th><th>Part</th><th>Serial</th><th>Cond</th><th>Date</th><th>POD</th></tr>`;available.forEach(r=>at.innerHTML+=`<tr><td>${r.user}</td><td>${r.loc}</td><td>${r.mat}</td><td>${r.part}</td><td>${r.serial}</td><td>${r.condition||r.adminCond}</td><td>${r.date}</td><td>${r.pod}</td></tr>`);}let faulty=getFiltered(returnList).filter(r=>r.condition=="Faulty");let ft=document.getElementById("faultyTable");if(ft){ft.innerHTML=`<tr><th>User</th><th>Material</th><th>Old Serial</th><th>Current Serial</th><th>Status</th><th>Side</th></tr>`;faulty.forEach(r=>ft.innerHTML+=`<tr><td>${r.user}</td><td>${r.oldMat||r.mat}</td><td>${r.oldSerial}</td><td>${r.serial}</td><td>${r.userStatus}</td><td>${r.sideCode}</td></tr>`);}}
function calcAmount(){let el=document.getElementById("tAmt");if(el)el.value=(document.getElementById("tDist").value*3)||0;}
function addTada(){let obj={id:Date.now(),user:currentUser.id,loc:currentUser.loc,date:tDate.value,side:tSide.value,incident:tIncident.value,from:tFrom.value,to:tTo.value,addr:tAddr.value,dist:parseFloat(tDist.value)||0,amt:parseFloat(tAmt.value)||0,work:tWork.value};tadaList.push(obj);saveData();renderTada();}
function renderTada(){let s=document.getElementById("tSearch")?.value.toLowerCase()||"";let f=document.getElementById("tFilter")?.value||"";let base=getFiltered(tadaList);currentTadaData=base.filter(t=>(t.incident.toLowerCase().includes(s)||t.user.toLowerCase().includes(s))&&(f==""||t.work==f));let tbl=document.getElementById("tadaTable");if(!tbl)return;tbl.innerHTML=`<tr><th>Date</th><th>User</th><th>Loc</th><th>Incident</th><th>Side</th><th>From-To</th><th>Dist</th><th>Work</th><th>Amt</th><th>Action</th></tr>`;currentTadaData.forEach(t=>tbl.innerHTML+=`<tr><td>${t.date}</td><td>${t.user}</td><td>${t.loc}</td><td>${t.incident}</td><td>${t.side}</td><td>${t.from} to ${t.to}</td><td>${t.dist}</td><td>${t.work}</td><td>Rs ${t.amt}</td><td><button class="btn-del" onclick="delTada(${t.id})">Del</button></td></tr>`);let td=currentTadaData.reduce((a,b)=>a+b.dist,0);let ta=currentTadaData.reduce((a,b)=>a+b.amt,0);let tot=document.getElementById("tTotal");if(tot)tot.innerText=`Records: ${currentTadaData.length} | Distance: ${td} KM | Amount: Rs ${ta}`;}
function delTada(id){tadaList=tadaList.filter(t=>t.id!=id);saveData();renderTada();}
function exportTadaExcel(){let ws=XLSX.utils.json_to_sheet(currentTadaData);let wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"TA-DA");XLSX.writeFile(wb,"TA-DA_"+currentUser.id+".xlsx");}
function exportTadaPDF(){const{jsPDF}=window.jspdf;let doc=new jsPDF('landscape');doc.text("TA-DA - "+currentUser.id,14,15);doc.autoTable({startY:20,html:'#tadaTable'});doc.save("TA-DA.pdf");}